
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 19 18:59:28 CST 2021
//----------------------------------------------------

package tarea6;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int NUM = 2;
  public static final int MENOS = 8;
  public static final int PUNTO_COMA = 11;
  public static final int POR = 4;
  public static final int P_C = 6;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int P_A = 5;
  public static final int DIV = 9;
  public static final int ID = 7;
  public static final int IGUAL = 10;
  public static final int error = 1;
}

